apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dfck8twt4-python
  janus-idp.io/tekton: dfck8twt4-python
  backstage.io/kubernetes-id: dfck8twt4-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dfck8twt4-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
